### ISSUE TITLE
Custom cloth problem

### ISSUE THREAD

**Issue by xorbs** [AngelliaX/Clothes#5]
![image](https://user-images.githubusercontent.com/29349731/77996102-f526ae00-7367-11ea-81c3-610b6a0cb2c0.png)

I put new Custom Model..
How can I fix it?

**Comment by TungstenVn** [comment]
that happened because you remove steve geometry in the .json file

**Comment by xorbs** [comment]
{
	"format_version": "1.12.0",
	"minecraft:geometry": [
		{
			"description": {
				"identifier": "geometry.lefthand",
				"texture_width": 16,
				"texture_height": 16,
				"visible_bounds_width": 2,
				"visible_bounds_height": 3,
				"visible_bounds_offset": [0, 1.5, 0]

here..?

**Comment by xorbs** [comment]
ex : sword.png   /   sword.geo.json 

How can I add it?

These have different filename ..

**Comment by Johnsonk79** [comment]
yeah it will be cool if you can teach us how to add our own geometries in readme

**Comment by TungstenVn** [comment]
you can use the clothes inside the plugin as example

1.The .json file
 -you should use the .json in the config then draw inside it because you need to have the steve geometry
 -the geometry name, you need to named it to "geometry.xyz"
  xyz is the folder name you putted the clothes in (take a look at the example .json file)
2.The .png
 -just draw a texture then saved
after you have 2 files above, you named them with the same name, for ex:
Angle_1.json , Angle_1.png
then put them in a folder named xyz then it ready to go

**Comment by Johnsonk79** [comment]
thx, will try

**Comment by benda95280** [comment]
So the JSON contain player model and shield ?
Is there any way to get current geometry of the player in the script, and push model of the shield into ?

Thanks

**Comment by TungstenVn** [comment]
Yes you can but you need to copy the code in the shield into the player geometry yourself.
As i know there is no tool to merge 2 bedrock model (geometry) file into one
